Erweiterung des Plugins um diverse Funktionen
plentymarkets/plugin-social-media pull request #1
Opened 2018-03-09 10:22 UTC by JVolke

- Ein weiterer Container für die Anzeiger Buttons direkt am Artikel (SocialMediaSingleItem)
- Für jeden Container können individuelle Einstellungen getroffen werden
- Option hinzugefügt, sodass per Konfiguration entschieden werden kann, ob eine feste URL oder dynamische URLs geteilt werden können sollen 
- Grund CSS für zweiten Container hinzugefügt
- Auswahl hinzugefügt, sodass das die Darstellung der Buttons je Container via Dropdown Liste ausgewählt werden kann (Alle shariff Themen stehen zur Auswahl)
- Konfiguration überarbeitet und einige Bereich etwas umbenannt
- UserGuide in Deutsch aktualisiert / Changelog aktualisiert

2018-03-09 10:41 UTC, dbohla commented
@Strean1337 Könntest du den PR bitte reviewen
@fmutschler Könntest du bitte User Guide und Changelog reviewen

Thx

2018-03-09 13:03 UTC, JVolke commented
Ich habe noch einen Fehler entdeckt: in den Dateien  SocialMedia.twig und SocialMediaSingleItem.twig

muss die if-Abfrage in Zeile 26 wie folgt lauten: {% if socialFixed != "false"  %} da ansonsten anscheinend beim An und Abwählen die Änderung sonst nicht übernommen wird.

2018-04-13 12:23 UTC, Sebsta13 requested changes

2018-04-13 12:23 UTC, Sebsta13 commented on meta/documents/user_guide_de.md
> +4. Wählen Sie den Container **SingleItem: After "Add to shopping cart" Button**, es kann alternativ natürlich auch ein anderer Container zu Anzeige genutzt werden.
Dieser container: **Single item: Additional content after "Add to shopping cart" button** würde sich besser eignen, da die buttons vom style her besser passen

2018-04-13 12:23 UTC, Sebsta13 commented on resources/views/content/SocialMedia.twig
> +    {% if socialFixed != "false"  %}
socialFixed == "true" steigert die lesbarkeit

2018-04-13 12:23 UTC, Sebsta13 commented on resources/views/content/SocialMediaSingleItem.twig
> +    {% if socialFixed != "false" %}
hier wieder == "true"

2018-04-13 12:24 UTC, Strean1337 commented
ich habe nur kleine Anpassungen an deinem Code. Im großen und ganzen finde ich es gelungen und vielen dank für die Neuerungen :)

2018-04-13 12:25 UTC, Strean1337 commented
@fmutschler könntest du nochmal über die Texte schauen und diese ggf. anpassen?

2018-04-13 12:27 UTC, Strean1337 commented on resources/views/content/SocialMedia.twig
> +    {% if socialFixed != "false"  %}
das sollte auch funktionieren, ich habe gesehen das du es von true auf false geändert hattest, allerdings war dein Fehler, dass du vorher auf: true und nicht auf "true" überprüft hast. Wir kriegen aus der config keinen wirklichen bool Wert zurück

2018-04-13 13:57 UTC, fmutschler requested changes

2018-04-13 13:57 UTC, fmutschler commented on meta/documents/changelog_de.md
> +- Ein weiterer Container für die Anzeiger Buttons direkt am Artikel
"Anzeiger Buttons" ist grammatikalisch nicht ganz sauber. Ich schlage "Anzeige-Buttons" vor.

2018-04-13 13:57 UTC, fmutschler commented on meta/documents/changelog_de.md
> +- Auswahl hinzugefügt, sodass das die Darstellung der Buttons je Container via Dropdown Liste ausgewählt werden kann
"das" muss gestrichen werden: "Auswahl hinzugefügt, sodass die Darstellung..."

2018-04-13 13:57 UTC, fmutschler commented on meta/documents/changelog_de.md
> +- Ein weiterer Container für die Anzeiger Buttons direkt am Artikel
Ich schlage ebenfalls vor den Eintrag mit "wurde hinzugefügt" zu beschließen, das hast du in den drei letzten Einträgen ebenfalls gemacht.

2018-04-13 13:57 UTC, fmutschler commented on meta/documents/user_guide_de.md
> +Ab Version 1.1.0 gibt es einen zweiten Container für die Darstellung der Social Buttons direkt am Artikel. Daneben wurden die Konfigurationsmöglichkeiten erweitert. Es gibt zwei Container einmal den
"Es gibt die zwei Container SocialMedia und SocialMediaSingleItem."

2018-04-13 13:57 UTC, fmutschler commented on meta/documents/user_guide_de.md
> +<td>Wählen Sie die Darstellung der Social Buttons aus, es stehen vier Themen zur Auswahl: Standard, Grey, White und Minimal</td>
Wählen Sie die Darstellung der Social Buttons aus. Es stehen vier Themen zur Auswahl: Standard, Grey, White und Minimal.

2018-04-13 13:57 UTC, fmutschler commented on meta/documents/user_guide_de.md
> +<td>Ist kein Haken gesetzt, wird immer die aktuell offene Seite mit den dort vorhandenen Medien-Informationen geteilt. Setzen Sie ein Haken, dann wird immer eine feste URL, ein fixer Text und ein fix
Setzen Sie ein Haken -> "Wenn Sie einen Haken setzen, wird immer..."

2018-04-13 13:57 UTC, fmutschler commented on meta/documents/user_guide_de.md
> +<td>Hinterlegen Sie hier die URL die geteilt werden soll, bspw. die URL Ihrer Startseite</td>
Punkt am Ende des Satzes einfügen.

2018-04-13 13:57 UTC, fmutschler commented on meta/documents/changelog_de.md
> +- Auswahl hinzugefügt, sodass das die Darstellung der Buttons je Container via Dropdown Liste ausgewählt werden kann
"Dropdown-Liste" sollte man tendenziell mit Bindestrich schreiben.

2018-04-13 14:39 UTC, fmutschler submitted a review, later dismissed

2018-04-13 14:39 UTC, fmutschler commented on config.json
> +    "label"                         : "Use fixe Social Media Text, URL and Image",
"Use fixed Social Media Text, URL and Image"

2018-04-13 14:39 UTC, fmutschler commented on config.json
>  [
Bitte einmal das Dokument auf Kohärenz bei der Groß- und Kleinschreibung von "Social Media" überprüfen. In Zeile 25 wird es bspw. groß geschrieben, in Zeile 46 wird "media" klein geschrieben.

Gleiches gilt für "text" und "image"

2018-04-14 04:18 UTC, JVolke commented
@Strean1337 und @fmutschler 
Danke für das Feedback. Ich habe die genannten Änderung umgesetzt.

2018-04-16 07:41 UTC, Strean1337 commented
@JVolke könntest du noch die merge Konflikte beheben? Sobald du die behoben hast, finde ich die Änderungen so in Ordnung und würde sie mergen.

2018-05-04 12:02 UTC, dbohla commented
@Strean1337 

Ich habe nun mal die Merge Conflicts behoben. Es war nur die Version... Bitte erneut gegen checken, da noch **Changes requested** sind oder approven und mergen.

2018-05-09 02:44 UTC, JVolke commented
@Strean1337
Kurze Frage, aktuell wird sowohl in Ceres, als auch im SocialMedia Plugin die shariff.min.css eingebunden. Hier könnte man doch die Einbindung noch aus dem SocialMedia Plugin entfernen, wenn gewährleistet ist, dass shariff-CSS bereits von Ceres bereitgestellt wird oder?

2018-05-24 15:52 UTC, Strean1337 commented
@JVolke in Ceres wird es zwar aktuell noch eingebunden, allerdings ist das vermutlich noch ein Überbleibsel aus der Zeit in der die Social Media-Funktionalitäten noch nativ in Ceres integriert waren und noch nicht aus einem eigenen Plugin kamen. Ich bin gerade dabei es zu entfernen und einen PR gegen Development zu stellen. Das ganze werde ich allerdings morgen Früh noch einmal mit dem gesamten Team absprechen bevor wir das Umsetzen.

2018-05-25 11:38 UTC, Strean1337 commented
@JVolke nach Absprache mit dem Team, haben wir uns dazu entschieden die Lib aus Ceres nativ zu entfernen. Der PR von mir wird gegen Development gestellt und wird in ca. 4 Wochen in Stable sein. 

Ich werde deine Änderungen nun mergen und mich um den Release der neuen Plugin Version kümmern.

Vielen dank für deinen Einsatz!

2018-05-25 11:38 UTC, Sebsta13 approved these changes

2018-05-25 11:46 UTC, fmutschler commented on meta/documents/user_guide_de.md
> +1. Klicken Sie auf **Plugins**.
Dieses Menü befindet sich nun unter CMS » Container-Verknüpfungen

2018-05-25 11:47 UTC, fmutschler commented on meta/documents/user_guide_de.md
> +2. Wechseln Sie in das Tab **Content**.
Dieses Menü befindet sich nun unter CMS » Container-Verknüpfungen

2018-05-25 11:47 UTC, Strean1337 commented on meta/documents/user_guide_de.md
> +1. Klicken Sie auf **Plugins**.
passe ich an.

2018-05-25 11:47 UTC, Strean1337 commented on meta/documents/user_guide_de.md
> +2. Wechseln Sie in das Tab **Content**.
passe ich an.

2018-05-25 12:11 UTC, fmutschler approved these changes

2018-05-25 12:16 UTC, fmutschler commented
Ich habe jetzt noch ein paar Änderungen gemacht, um die Texte plenty-Styleguide konform zu machen; dazu gehören auch Änderungen, die entgegen meiner vorherigen Kommentare gehen. Daher erstmal eine Entschuldigung an Jens meinerseits, meine obige Anmerkung zu Groß-/Kleinschreibung war beispielsweise nicht Styleguide-konform - aber man lernt ja auch immer dazu :) In jedem Fall ein richtig dickes Dankeschön an dich, Jens, dass du uns so unter die Arme greifst!

2018-05-25 12:23 UTC, JVolke commented
@Strean1337 Danke für die Info, dann muss ich darauf achten, da ich es aktuell nicht mehr zusätzlich bei mir einbinde
@fmutschler Kein Problem und gern geschehen :)

2018-05-25 12:43 UTC, merged